stock/urls.py
from django.urls import path
from . import views

app_name = 'stock'
urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('stock_list/', views.StockListView.as_view(), name='stock_list'),
    path('create_item/', views.create_item, name='create_item'),
    path('delete_item/<int:item_id>/', views.delete_item, name='delete_item'),
    path('update_item/<int:item_id>/', views.update_item, name='update_item'),
    path('increase_quantity/<int:item_id>', views.increase_item_quantity, name='increase_item_quantity'),
    path('decrease_quantity/<int:item_id>', views.decrease_item_quantity, name='decrease_item_quantity'),
    path('detail_item/<int:pk>', views.StockDetailView.as_view(), name='detail_item'),
    path('stock_sell_list/', views.StockSellListView.as_view(), name='stock_sell_list'),
    path('stock_sell_analysis/<int:sold_id>', views.stock_sell_analysis, name='stock_sell_analysis'),
    path('create_sell_report/', views.create_sell_report, name='create_sell_report'),
    path('clear_all_sold/', views.clear_all_sold, name='clear_all_sold'),
]

stock_system_management/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stock.urls')),
]

stock/models.py
from django.db import models

# Create your models here.
class Item(models.Model):
    name = models.TextField(max_length=50)
    category = models.TextField(max_length=50)
    quantity = models.IntegerField()
    acquisition_price = models.FloatField(null=True)
    sell_price = models.FloatField()
    discount = models.BooleanField(default=False)
    discount_percentage = models.IntegerField(default=0)
    supplier = models.TextField(max_length=50, null=True)
    created_at = models.DateTimeField()
    modified_at = models.DateTimeField()
    sold_quantity = models.IntegerField(default=0)

stock/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from .models import Item
from fpdf import FPDF
from fpdf.fonts import FontFace
import datetime
import csv

# Create your views here.
class Index(generic.TemplateView):
    template_name = 'stock/index.html'

class StockDetailView(generic.DetailView):
    model = Item
    template_name = 'stock/stock_detail.html'

class StockListView(generic.ListView):
    template_name = 'stock/stock_list.html'
    context_object_name = "items"

    def get_queryset(self):
        return Item.objects.all().order_by('id')

class StockSellListView(generic.ListView):
    template_name = 'stock/stock_sell_list.html'
    context_object_name = 'sell_item'

    def get_queryset(self):
        return Item.objects.all().order_by('id')

def stock_sell_analysis(request, sold_id):
    sold = request.POST["sold"]
    item_sold = Item.objects.get(id=sold_id)
    item_sold.sold_quantity = sold
    item_sold.save()
    return redirect(reverse('stock:stock_sell_list'))

def create_sell_report(request):
    option_choice = request.POST.getlist("inlineRadioOptions")
    if option_choice[0] == 'csv':
        today = datetime.datetime.today().date()
        response = HttpResponse(
            content_type="text/csv",
            headers={"Content-Disposition": f'attachment; filename="Seal-Inform-{today}.csv"'},
        )
        writer = csv.writer(response)
        writer.writerow(["Daily Sales Inform", f"Date: {today}"])
        writer.writerow([
            "Name", "Category", "Quantity (Sold)", "Acquisition Price", "Sell Price",
            "On Discount", "Discount Percentage", "Supplier", "Arrival Date", "Latest Modified Date",
        ])
        for item in Item.objects.all():
            writer.writerow([
                item.name,
                item.category,
                f"{item.quantity} ({item.sold_quantity})",
                item.acquisition_price,
                item.sell_price,
                item.discount,
                item.discount_percentage,
                item.supplier,
                item.created_at,
                item.modified_at,
            ])
        return response
    elif option_choice[0] == 'pdf':
        today = datetime.datetime.today().date()
        data = [
            ["Name", "Category", "Quantity (Sold)", "Acquisition Price", "Sell Price",
            "On Discount", "Discount Percentage", "Supplier", "Arrival Date", "Latest Modified Date",]
        ]
        items = Item.objects.all()
        for item in items:
            data.append([
                item.name, item.category, f"{item.quantity} ({item.sold_quantity})", f"{item.acquisition_price}",
                f"{item.sell_price}", f"{item.discount}", f"{item.discount_percentage}", f"{item.supplier}",
                f"{item.created_at.today()}", f"{item.modified_at.today()}",
            ])
        pdf = FPDF()
        pdf.set_font("helvetica", size=8)

        # Styled table:
        pdf.add_page()
        pdf.set_draw_color(190, 190, 190)
        pdf.set_line_width(0.3)
        pdf.set_margins(0, 5, 5)
        headings_style = FontFace(emphasis="BOLD", color=255, fill_color=(47, 31, 92))
        with pdf.table(
            borders_layout="MINIMAL",
            cell_fill_color=(224, 235, 255),
            col_widths=20,
            headings_style=headings_style,
            line_height=5,
            text_align="CENTER",
            width=190,
        ) as table:
            for data_row in data:
                row = table.row()
                for datum in data_row:
                    row.cell(datum)
        response = HttpResponse(bytes(pdf.output()), content_type='application/pdf')
        response['Content-Disposition'] = f"attachment; filename=Seal-Inform-{today}.pdf"
        return response
    else:
        return redirect(reverse('stock:stock_list'))

def create_item(request):
    item_name = request.POST["item_name"]
    item_category = request.POST["item_category"]
    item_quantity = request.POST["item_quantity"]
    item_acquisition_price = request.POST["item_acquisition_price"]
    item_sell_price = request.POST["item_sell_price"]
    item_supplier = request.POST["item_supplier"]
    new_item = Item(
        name=item_name,
        category=item_category,
        quantity=item_quantity,
        acquisition_price=item_acquisition_price,
        sell_price=item_sell_price,
        supplier=item_supplier,
        created_at=timezone.now(),
        modified_at=timezone.now(),
    )
    new_item.save()
    return redirect(reverse('stock:index'))

def delete_item(request, item_id):
    del_item = Item.objects.get(id=item_id)
    del_item.delete()
    return redirect(reverse('stock:stock_list'))

def update_item(request, item_id):
    update_name = request.POST["update_name"]
    update_category = request.POST["update_category"]
    update_quantity = request.POST["update_quantity"]
    update_acquisition_price = request.POST["update_acquisition_price"]
    update_sell_price = request.POST["update_sell_price"]
    update_supplier = request.POST["update_supplier"]
    updated_item = Item.objects.get(id=item_id)
    updated_item.name = update_name
    updated_item.category = update_category
    updated_item.quantity = update_quantity
    updated_item.acquisition_price = update_acquisition_price
    updated_item.sell_price = update_sell_price
    updated_item.supplier = update_supplier
    updated_item.modified_at = timezone.now()
    updated_item.save()
    return redirect(reverse('stock:stock_list'))

def increase_item_quantity(request, item_id):
    increase_quantity = request.POST['increase_quantity']
    increase_item = Item.objects.get(id=item_id)
    increase_item.quantity += int(increase_quantity)
    increase_item.modified_at = timezone.now()
    increase_item.save()
    return redirect(reverse('stock:stock_list'))

def decrease_item_quantity(request, item_id):
    decrease_quantity = request.POST['decrease_quantity']
    increase_item = Item.objects.get(id=item_id)
    increase_item.quantity -= int(decrease_quantity)
    increase_item.modified_at = timezone.now()
    increase_item.save()
    return redirect(reverse('stock:stock_list'))

def clear_all_sold(request):
    items = Item.objects.all()
    for item in items:
        item.sold_quantity = 0
        item.save()
    return redirect(reverse('stock:stock_sell_list'))

stock/templates/stock/stock_detail.html
{% load static %}
{% load mathfilters %}

<link href="{% static 'stock/mdb5-free-standard/css/mdb.min.css' %}" rel="stylesheet" type="text/css"/>

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- MDB -->
    <link
    href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.0/mdb.min.css"
    rel="stylesheet"
    />
    <title>Document</title>
  </head>
  <body>
    <!-- header -->
    {% include "stock/header.html" %}

    <div class="d-flex mt-5 table-responsive p-3 row">
        <div class="table-responsive col-12">
            <table class="table caption-top bg-secondary text-light table-hover table-borderless">
                <caption>
                  <h3 class="text-center">Detailed Item View</h3>
                </caption>
                <thead class="table-dark">
                    <tr>
                        <th scope="col">Item</th>
                        <th scope="col">Name</th>
                        <th scope="col">Category</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Acquisition Price</th>
                        <th scope="col">Sell Price</th>
                        <th scope="col">On Discount</th>
                        <th scope="col">Discount Percentage</th>
                        <th scope="col">Supplier</th>
                        <th scope="col">Arrival Date</th>
                        <th scope="col">Latest Modified Date</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <tr class="item">
                        <th scope="row">{{ item.id }}</th>
                        <td>{{ item.name }}</td>
                        <td>{{ item.category }}</td>
                        <td>{{ item.quantity }}</td>
                        <td>{{ item.acquisition_price }}</td>
                        <td>{{ item.sell_price }}</td>
                        <td>{{ item.discount }}</td>
                        <td>{{ item.discount_percentage }}</td>
                        <td>{{ item.supplier }}</td>
                        <td>{{ item.created_at }}</td>
                        <td>{{ item.modified_at }}</td>
                        <td>
                          <div class="btn-group btn-group-sm shadow-0" role="group">
                            <form action="{% url 'stock:update_item' item.id %}" method="post">
                              {% csrf_token %}
                              <button type="button" class="btn btn-success btn-floating" data-mdb-color="dark" data-mdb-toggle="modal" data-mdb-target="#exampleModal">
                                <span style="font-size: 1.4rem;">&#9850;</span>
                              </button>
                              <!-- Modal -->
                              <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Edit Item</h5>
                                            <button type="button" class="btn-close" data-mdb-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            <!-- name input -->
                                            <div class="form-outline mb-4">
                                                <input type="text" id="formname" class="form-control" name="update_name" value="{{ item.name }}" />
                                                <label class="form-label" for="formname">Item Name</label>
                                            </div>
                                            <!-- category input -->
                                            <div class="form-outline mb-4">
                                                <input type="text" id="formcategory" class="form-control" name="update_category" value="{{ item.category }}" />
                                                <label class="form-label" for="formcategory">Item Category</label>
                                            </div>
                                            <!-- quantity input -->
                                            <div class="form-outline mb-4">
                                                <input type="text" id="formquantity" class="form-control" name="update_quantity" value="{{ item.quantity }}" />
                                                <label class="form-label" for="formquantity">Quantity</label>
                                            </div>
                                            <!-- acquisition_price input -->
                                            <div class="form-outline mb-4">
                                                <input type="text" id="formacqprice" class="form-control" name="update_acquisition_price" value="{{ item.acquisition_price }}" />
                                                <label class="form-label" for="formacqprice">Acquisition Price</label>
                                            </div>
                                            <!-- sell_price input -->
                                            <div class="form-outline mb-4">
                                                <input type="text" id="formsellprice" class="form-control" name="update_sell_price" value="{{ item.sell_price }}" />
                                                <label class="form-label" for="formsellprice">Sell Price</label>
                                            </div>
                                            <!-- supplier input -->
                                            <div class="form-outline mb-4">
                                                <input type="text" id="formsupplier" class="form-control" name="update_supplier" value="{{ item.supplier}}" />
                                                <label class="form-label" for="formsupplier">Supplier</label>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-mdb-dismiss="modal">Close</button>
                                            <button type="submit" class="btn btn-primary">Save changes</button>
                                        </div>
                                    </div>
                                </div>
                              </div>
                            </form>
                            <form action="{% url 'stock:increase_item_quantity' item.id %}" method="post">
                              {% csrf_token %}
                              <button type="submit" class="btn btn-info btn-floating" data-mdb-color="dark" data-mdb-toggle="modal" data-mdb-target="#incrementModal">
                                <span style="font-size: 1.4rem;">&#10010;</span>
                              </button>
                              <!-- Modal -->
                              <div class="modal fade" id="incrementModal" tabindex="-1" aria-labelledby="incrementModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="incrementModalLabel">Edit {{ item.name }} quantity</h5>
                                            <button type="button" class="btn-close" data-mdb-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            <!-- quantity input -->
                                            <div class="form-outline mb-4">
                                                <input type="text" id="formincrease" class="form-control" name="increase_quantity" required />
                                                <label class="form-label" for="formincrease">Quantity</label>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-mdb-dismiss="modal">Close</button>
                                            <button type="submit" class="btn btn-primary">Increment Item quantity</button>
                                        </div>
                                    </div>
                                </div>
                              </div>
                            </form>
                            <form action="{% url 'stock:decrease_item_quantity' item.id %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger btn-floating" data-mdb-color="dark" data-mdb-toggle="modal" data-mdb-target="#decrementModal">
                                  <span style="font-size: 1.4rem;">&#8722;</span>
                                </button>
                                <!-- Modal -->
                              <div class="modal fade" id="decrementModal" tabindex="-1" aria-labelledby="decrementModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="decrementModalLabel">Edit {{ item.name }} quantity</h5>
                                            <button type="button" class="btn-close" data-mdb-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            <!-- quantity input -->
                                            <div class="form-outline mb-4">
                                                <input type="text" id="formdecrease" class="form-control" name="decrease_quantity" required />
                                                <label class="form-label" for="formdecrease">Quantity</label>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-mdb-dismiss="modal">Close</button>
                                            <button type="submit" class="btn btn-primary">Decrement Item quantity</button>
                                        </div>
                                    </div>
                                </div>
                              </div>
                            </form>
                          </div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-12 text-center">
            Total earnings: &#x24; {{ item.sell_price|sub:item.acquisition_price|mul:item.quantity }}
        </div>
        <div class="col-12 text-center">
            Earnings per unity: &#x24; {{ item.sell_price|sub:item.acquisition_price }}
        </div>
        <div class="col-12 text-center mt-2">
            <a href="{% url 'stock:stock_list' %}" class="btn btn-primary">Back</a>
        </div>
    </div>
    <script src="{% static 'stock/mdb5-free-standard/js/mdb.min.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <script src="{% static 'js/jquery-3.6.4.min.js' %}"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.0/mdb.min.js"></script>
  </body>
</html>

stock/templates/stock/stock_list.html
{% load static %}

<link href="{% static 'stock/mdb5-free-standard/css/mdb.min.css' %}" rel="stylesheet" type="text/css"/>

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- MDB -->
    <link
    href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.0/mdb.min.css"
    rel="stylesheet"
    />
    <title>Document</title>
  </head>
  <body>
    <!-- header -->
    {% include "stock/header.html" %}

    <div class="d-flex mt-5 table-responsive p-3" style="height: 33rem;">
        {% if items %}
            <div class="table-responsive">
                <table class="table caption-top bg-secondary text-light table-hover table-borderless overflow-y-scroll">
                    <caption>
                      <h3 class="text-center">Items Table</h3>
                    </caption>
                    <thead class="table-dark">
                        <tr>
                            <th scope="col">Item</th>
                            <th scope="col">Name</th>
                            <th scope="col">Category</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Acquisition Price</th>
                            <th scope="col">Sell Price</th>
                            <th scope="col">On Discount</th>
                            <th scope="col">Discount Percentage</th>
                            <th scope="col">Supplier</th>
                            <th scope="col">Arrival Date</th>
                            <th scope="col">Latest Modified Date</th>
                            <th scope="col">Details</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in items %}
                            <tr class="item">
                                <th scope="row">{{ item.id }}</th>
                                <td>{{ item.name }}</td>
                                <td>{{ item.category }}</td>
                                <td>{{ item.quantity }}</td>
                                <td>{{ item.acquisition_price }}</td>
                                <td>{{ item.sell_price }}</td>
                                <td>{{ item.discount }}</td>
                                <td>{{ item.discount_percentage }}</td>
                                <td>{{ item.supplier }}</td>
                                <td>{{ item.created_at }}</td>
                                <td>{{ item.modified_at }}</td>
                                <td>
                                  <div class="btn-group btn-group-sm shadow-0" role="group">
                                    <form action="{% url 'stock:detail_item' item.id %}">
                                      {% csrf_token %}
                                      <button type="submit" class="btn btn-primary btn-floating" data-mdb-color="dark">
                                        <span style="font-size: 1.4rem;">&#9998;</span>
                                      </button>
                                    </form>
                                    <form action="{% url 'stock:delete_item' item.id %}" method="post">
                                      {% csrf_token %}
                                      <button type="submit" class="btn btn-danger btn-floating" data-mdb-color="dark">
                                        <span style="font-size: 1.4rem;">&#128465;</span>
                                      </button>
                                    </form>
                                  </div>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <input class="form-control mb-3" id="mySearch" type="text" placeholder="Search Item By Any field...">
            </div>
        {% else %}
            <p>Empty Stock. Please add items.</p>
        {% endif %}
    </div>
    <script src="{% static 'stock/mdb5-free-standard/js/mdb.min.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <script src="{% static 'js/jquery-3.6.4.min.js' %}"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.0/mdb.min.js"></script>
    <script>
      $(document).ready(function(){
        $('#mySearch').on("keyup", function(){
          var value = $(this).val().toLowerCase();
          $('.item').filter(function(){
            $(this).toggle(
              $(this).text().toLowerCase().indexOf(value) > -1
            );
          })
        });
      })
    </script>
  </body>
</html>

stock/templates/stock/stock_sell_list.html
{% load static %}

<link href="{% static 'stock/mdb5-free-standard/css/mdb.min.css' %}" rel="stylesheet" type="text/css"/>

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- MDB -->
    <link
    href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.0/mdb.min.css"
    rel="stylesheet"
    />
    <title>Document</title>
  </head>
  <body>
    <!-- header -->
    {% include "stock/header.html" %}

    <div class="d-flex mt-5 table-responsive p-3" style="height: 33rem;">
        {% if sell_item %}
          <div class="table-responsive">
            <table class="table caption-top bg-secondary text-light table-hover table-borderless overflow-y-scroll">
              <caption>
                <h3 class="text-center">Daily Items Sale Report Section</h3>
              </caption>
              <thead class="table-dark">
                  <tr>
                      <th scope="col">Item</th>
                      <th scope="col">Name</th>
                      <th scope="col">Category</th>
                      <th scope="col">Quantity</th>
                      <th scope="col">Acquisition Price</th>
                      <th scope="col">Sell Price</th>
                      <th scope="col">On Discount</th>
                      <th scope="col">Discount Percentage</th>
                      <th scope="col">Supplier</th>
                      <th scope="col">Arrival Date</th>
                      <th scope="col">Latest Modified Date</th>
                      <th scope="col">Sold</th>
                  </tr>
              </thead>
              <tbody>
                  {% for item in sell_item %}
                      <tr class="item">
                          <th scope="row">{{ item.id }}</th>
                          <td>{{ item.name }}</td>
                          <td>{{ item.category }}</td>
                          <td>{{ item.quantity }}</td>
                          <td>{{ item.acquisition_price }}</td>
                          <td>{{ item.sell_price }}</td>
                          <td>{{ item.discount }}</td>
                          <td>{{ item.discount_percentage }}</td>
                          <td>{{ item.supplier }}</td>
                          <td>{{ item.created_at }}</td>
                          <td>{{ item.modified_at }}</td>
                          <td>
                            <div class="container">
                              <form class="table-responsive" action="{% url 'stock:stock_sell_analysis' item.id %}" method="post">
                                {% csrf_token %}
                                <div class="input-group">
                                  <div class="form-outline">
                                    <input type="text" class="form-control" name="sold" style="width: 3rem;" value="{{ item.sold_quantity }}" required>
                                  </div>
                                  <button type="submit" class="btn btn-primary">Confirm</button>
                                </div>
                              </form>
                            </div>
                          </td>
                      </tr>
                  {% endfor %}
              </tbody>
            </table>
            <div class="row">
              <div class="col-6 text-center mt-2">
                <form action="{% url 'stock:create_sell_report' %}" method="post">
                  {% csrf_token %}
                  <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="csv" />
                    <label class="form-check-label" for="inlineRadio1">csv</label>
                  </div>
                  <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="pdf" />
                    <label class="form-check-label" for="inlineRadio2">pdf</label>
                  </div>
                  <div class="col-12 text-center mt-2">
                    <button type="submit" class="btn btn-primary">Generate Report</button>
                  </div>
                </form>
              </div>
              <div class="col-6 text-center mt-2">
                <form class="table-responsive" action="{% url 'stock:clear_all_sold' %}" method="post">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-primary">Clear Sold Entries</button>
                </form>
              </div>
            </div>
          </div>
        {% else %}
            <p>Empty Stock. Not Analysis allowed.</p>
        {% endif %}
    </div>
    <script src="{% static 'stock/mdb5-free-standard/js/mdb.min.js' %}"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.0/mdb.min.js"></script>
  </body>
</html>